### ISSUE TITLE
Counter resets althought wire is not active

### ISSUE THREAD

**Issue by MaxiDoet** [logisim-evolution/logisim-evolution#1396]
I'd like to build a clock divider but my counter gets reset by the comparator althought the values changed and the wire is not active

![image](https://user-images.githubusercontent.com/38401902/156167411-f8a5451c-e712-44ff-ae13-b38eef5e1ef8.png)

Here is my project:
If you test it don't forget to set the divider
[Project.zip](https://github.com/logisim-evolution/logisim-evolution/files/8161495/Project.zip)
![image](https://user-images.githubusercontent.com/38401902/156167709-fbfc7b50-5b93-4921-996b-920b90fabfa9.png)

**Comment by davidhutchens** [comment]
The circuit behavior seems to work for me. The reset input is asynchronous, so it resets as soon as the value of the counter hits the div value and does not wait for the next clock.

I suspect the behavior you desire can be obtained by moving the output of your OR from the R input to the M1 [load] input. Then it will wait for the next clock cycle to load the zero you have as the data input to your counter.

Does this solve the problem?

**Comment by MaxiDoet** [comment]
Have you opened the circuit and tried it? The counter resets even if no line is active thats my problem

**Comment by davidhutchens** [comment]
Yes, I did open the circuit and try it. And I do not see it resetting when no line is active. For example, if you change the value of div to 4, it resets after counting to 3. When it hits 4, the equality test is true for a very short instant which resets the counter to 0 which causes the equality to drop back to false. This happens quickly, before the next clock. Thus you never "see" the value at 4 or the Reset line as true.

**Comment by MaxiDoet** [comment]
Oops, my mistake. 
This is how i solved it: 
![image](https://user-images.githubusercontent.com/38401902/156194388-0fc9f341-afcf-45d3-b18c-9cf3e8ed03f0.png)

**Comment by maehne** [comment]
It is unreliable to use the asynchronous reset to implement the desired reset behaviour for the counter described by you. The reason are hazards due to the generation of the asynchronous reset signal with the help of a combinatoric circuit. Your fix above is fragile and might not work if the circuit gets synthesised on real hardware.

Instead, it is recommended to implement a synchronous reset behaviour. In the case of your circuit example, it should suffice to connect your reset condition signal to the load input. Loading zero into the counter at a rising clock edge corresponds to a synchronous reset.
