### ISSUE TITLE
 What does the shared label mean?

### ISSUE THREAD

**Issue by BreakingLead** [logisim-evolution/logisim-evolution#1618]
Sorry for the dumb question. I have read the manual but I still don't know what does it mean. I'm not a native English speaker so I'm sorry for any mistake.

**Comment by maehne** [comment]
@BreakingLead: Thanks for the question! Though, you could have provided a bit of more context, where did you find this term. I found it in a single location in the User's Guide section "Selecting the appearance of a subcircuit":

<img width="609" alt="Bildschirmfoto 2023-01-03 um 12 48 09" src="https://user-images.githubusercontent.com/1174243/210351583-72dd589c-1995-47dd-81de-b717b8adeead.png">
﻿
It seems that this shared label is not of much use today, as the default Logisim-evolution appearance as well as the Logisim-holycross appearance include the circuit name. Though in the Logisim-Classical appearance, the circuit is drawn as an unnamed rectangle, where the shared label seems to serve the purpose to make them distinguishable. So, this property seems to primarily exist for historic/backward compatibility reasons.

@BFH-ktt1: Please correct me if I am wrong.

@BreakingLead: I will close this issue since I think your question is answered. Feel free to reopen if you require further assistance.
