### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by 18001767679** [logisim-evolution/logisim-evolution#1634]
Why does the shape of the jtag uart fit the shape of a keyboard and a tty?
You could also drive those two using normal Parellel IO!

**Comment by maehne** [comment]
Because the JTAG UART serves as end point for the stdin and stdout stream for bare metal C programs. It models the behaviour of an IP block with the same name available in the Platform Design of Quartus Prime. The latter establishes a TTY connection over JTAG from your developer PC to the SOPC implemented on an FPGA. I'll close this issue as answered.
