### ISSUE TITLE
Version 3.8.0 still not released as snap

### ISSUE THREAD

**Issue by alculete** [logisim-evolution/logisim-evolution#1661]
Version 3.8.0 still not released as snap on stable channel. If possible, please update this channel

**Comment by R3dst0ne** [comment]
This is a known issue.
See #1534 and #1614.
#1647 describes view things that need to be addressed to fix this. 

I'd close this issue as duplicate.

**Comment by alculete** [comment]
Post the error you are having on [snapcraft forum](https://forum.snapcraft.io/)  they will help

**Comment by maehne** [comment]
@alculete: Do you have experience with creating snap packages and would be willing to help resolve this issue? We have limited ressources and need to prioritize. Typically this means resolving first pain points of our students and ourselves. Since we use it always in combination with FPGA synthesis tool chains, package formats that impose sandboxing have less priority for us.

**Comment by alculete** [comment]
Unfortunately no. I think you can ask snapcrafters for help or maybe ask them to take control of your snap releases

**Comment by MarcinOrlowski** [comment]
v3.8.0 is now in snap store.

**Comment by alculete** [comment]
Hi @MarcinOrlowski  the icon is still not available on the app menu. Still need to go through the terminal to open it
