### ISSUE TITLE
Rotating object through scroll.

### ISSUE THREAD

**Issue by GamePlayer-8** [logisim-evolution/logisim-evolution#1665]
Heyo,

As the title says. Is there would be an option to rotate an object through scroll? It would make setting up the circuit a bit faster.

**Comment by maehne** [comment]
Are you aware that you can rotate a selected component using the arrow keys?

**Comment by maehne** [comment]
Personally, I am not in favour: The scroll wheels should serve their main task, i.e., navigating on the schematic sheet. Using them to rotate a symbol is problematic, even if this would only become active when selecting a component, because typically you want the selection to stay active even while scrolling on the schematic sheet. At minimum, you would need some modifier key to be pressed for activating the rotation and then the difference to using the arrow keys becomes small.

That said: We are open to such kind of suggestions, but they need to be thought through and formulated in a more precise way, so that it becomes clear what behaviour is really wanted. Also potentially unwanted side effects of such a change need to be thoroughly analysed before investing time in implementing the feature. PRs are welcome! Just be aware that you might get challenged by the reviewers especially if the change is not well documented and justified.

**Comment by GamePlayer-8** [comment]
Rotating the object would work when was selected & cursor is on it.
