### ISSUE TITLE
Android version release

### ISSUE THREAD

**Issue by EchoCoder1729** [logisim-evolution/logisim-evolution#1826]
What can I do to port the application for Android ? Do I need to build it separately if at all that can be done.
What options do I have for running logisim on Android devices ?

**Comment by gtxzsxxk** [comment]
This might be a little bit hard and have few possibilities because the whole project is running on java swing framework, which is not supported by android platform. To make it possible, we need rewrite the gui codes, replacing them from the swing to something the android supports, which needs a lot of work. And we should consider the screen sizes and design their adpations, which are not that easy.

**Comment by maehne** [comment]
I agree with @gtxzsxxk assessment that porting to Android will be a very big effort due to the currently strong coupling of our code base to Swing. Contributions in this direction are welcome as long as it does not degrade the user experience on our three supported platforms Linux, macOS, and Windows. From our side, we don't have any resources to dedicate on such an effort apart from code reviews. For the moment, I will mark this issue as won't fix and close this issue, but feel free to reopen it for continuing the discussion or creating PRs.

**Comment by uzzy-buzzy** [comment]
> [#2066](https://github.com/logisim-evolution/logisim-evolution/discussions/2066) Download jre4android app from google Play; this app can run jar file

So can we set this up on our own or will those need to be done on the developer s side
