### ISSUE TITLE
All Gates - Red Output

### ISSUE THREAD

**Issue by amunrarara** [logisim-evolution/logisim-evolution#1972]
Cheers,

This is occurring on the 3 most recent releases. All projects have this issue, it's been a thing since I first downloaded, and it's negatively impacting my projects.
 
Here's some screenshots + my specs

![Screen Shot 2024-02-28 at 3 44 30 PM](https://github.com/logisim-evolution/logisim-evolution/assets/21048358/20abd30c-d584-4712-8e7c-9caf31743b92)

![Screen Shot 2024-02-28 at 3 48 03 PM](https://github.com/logisim-evolution/logisim-evolution/assets/21048358/c8723a0c-69d9-40e9-a823-346a01a337c3)

**Comment by davidhutchens** [comment]
Each of the output values in your picture matches the intended output for that situation.

The Switch connects the output to the input when it is on (i.e. 1) and disconnects it when it is off (i.e. 0). A disconnected output is not driven to any state and is thus floating (U), indicated by the blue color. All the switches in your picture are off (0).

If you provide inputs that have no known 0 or 1 value to a logic gate you will get an unknown result. It is not floating but an unknown logic value. That is designated in the simulator by an error (E) value displayed as red. It is a mistake to design hardware that uses such a value for further computations.

Likewise, using a U (blue) control value for a controlled buffer or inverter leaves the simulator with no way to display a meaningful output since it doesn't even know if it should drive the output or not. Thus that output is displayed as red (E) and should not be used.

So you should make sure your logic gates have well defined 0 or 1 inputs.

Read the Help for those components for more information.

**Comment by maehne** [comment]
To add to @davidhutchens very good answer: If you want to continue using the Switch for controlling your inputs, you need to add Pull Resistors with Pull Direction set to Zero to ensure that the inputs of the gates have a well-defined value if the Switch disconnects the input from the Power.
