### ISSUE TITLE
Combinational analysis malfunction in version 3.8

### ISSUE THREAD

**Issue by tecnozati** [logisim-evolution/logisim-evolution#1993]
The following image corresponds to a simplification poorly resolved with version 3.8:
![image](https://github.com/logisim-evolution/logisim-evolution/assets/135252348/853456a4-b5a4-4abd-a1e3-35145fad36a6)

The simplification well resolved with version 3.7.2 is the following image:

![image](https://github.com/logisim-evolution/logisim-evolution/assets/135252348/cfbb082f-24d4-483e-8a7c-1d3ca140c808)

I am doing something wrong?
Thank you very much for this fabulous software.

**Comment by davidhutchens** [comment]
PR #1938 recently made significant changes to how this part of our code works in our main branch. Could you look at our [nightly builds](https://github.com/logisim-evolution/logisim-evolution/actions/workflows/nightly.yml) and see if this issue has been fixed in development?

If the issue has been fixed, please note that here and close this issue. If not, please provide the actual input to the analysis that you used so we can reproduce it.

**Comment by tecnozati** [comment]
I find it impossible to test nightly builds.
To find this error, simply open combinational analysis, declare a, b and c as input variables and f as output variables, finally type the combination of the images in the minimized tab.

**Comment by maehne** [comment]
This is already fixed, as noted by @davidhutchens on our main branch. You can test it, e.g., with [this nightly build](https://github.com/logisim-evolution/logisim-evolution/actions/runs/8746288732).
