### ISSUE TITLE
Allow it to zoom out more of Logisim schematics

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#254]
Sometimes Logisim schematics get very wide and won't fit on a screen if manually zooming out. The zoom is currently limited to be >= 20 %. The `Auto` button already allows to zoom out below this value.

**Comment by MarcinOrlowski** [comment]
I reworked zoom controls so now you can go down as low as 5%. I also added 3 levels of granularity, so zoom step is smaller for lower values and increases for bigger zooms: step 5 up to 50%, then 10 up to 200% and 20 up to 1000%

**Comment by R3dst0ne** [comment]
Since #814 zooming in/out with the thumb pad can lead to very precise numbers.
![zoom_thumbpad_1](https://user-images.githubusercontent.com/62245695/126992176-4ff3783c-032e-4884-a846-c18cd63d62f6.PNG)
![zoom_thumbpad_2](https://user-images.githubusercontent.com/62245695/126992188-54782eb9-f774-439a-8c91-a2b807154ecf.PNG)
Using the `Auto` size button also sets very precise numbers.
![zoom_auto](https://user-images.githubusercontent.com/62245695/126992208-9f53111f-3d2d-43e9-b9a5-86eaebfe57d7.PNG)
In my opinion, the zoom values from these actions should align with the other types of zooming.

**Comment by MarcinOrlowski** [comment]
Oh :( I thought I was rounding this so something sane. Apparently not. Will fix it.
