### ISSUE TITLE
Critical path delay analysis

### ISSUE THREAD

**Issue by pr33ch** [logisim-evolution/logisim-evolution#337]
Hi everyone :) I am a student who is using logisim and had an idea for a feature. It would be pretty useful if there were a tool that could automatically find and highlight the critical path in the circuit while outputting an estimated delay based on delay models.

I am interested in implementing this feature and would love to learn the fastest way to get myself acquainted with the code base for developing this.

**Comment by maehne** [comment]
Yes, it would be a nice feature. However, this would mean that Logisim-evolution must be extended to allow specifying gate delays. This may be difficult as to my knowledge Logisim-evolution does not fully implement the concept of discrete time and event-driven simulation as HDL simulators such as ghdl or ModelSim do, but a more simplified one based purely on the events produced by the clock signals generator.

@BFH-ktt1 is more familiar with the internals of the Logisim-evolution implementation. Maybe he could comment on this issue and give you some guidance on what would be possible to implement with a reasonable effort. I am afraid the he and myself won't be as reactive as in previous months due to a busy semester, which will start next week.
