### ISSUE TITLE
Write enable pin missing from flip-flops

### ISSUE THREAD

**Issue by benburk** [logisim-evolution/logisim-evolution#401]
The write enable pin is missing from the different flip flop circuits. These were present on the original circuits as shown [here](http://www.cburch.com/logisim/docs/2.3.0/libs/mem/flipflops.html).

**Comment by ReGuess** [comment]
See #128 
Although I will say that either it ought to be brought back, or the documentation ought to be updated regarding this, and ought to explain how to recreate all four kinds of flip-flops using registers. The only one that's immediately obvious is the D flip-flop; and even still, registers lack the "preset/pin to 1 asynchronously" input pin available on the flip-flops.

**Comment by BFH-ktt1** [comment]
The documentation on the flipflops is not up to date, still on the todo list.  I agree that on the registers the asynchronous preset pin is missing and opt for this option rather than adding them to the flipflops. But I'm open for suggestions. Adding and enable pin to the flipflops in a sense is dubious as it can be implemented by a gated clock (in general not a good option) or by a feed-back that keeps the flipflop in it's current state (prefferred method). Please let me know what you think, it can be re-introduced by using an attribute for example.

**Comment by Triavanicus** [comment]
Here is an example on how to do this.
[FlipFlops.zip](https://github.com/reds-heig/logisim-evolution/files/4925021/FlipFlops.zip)

**Comment by LordDecapo** [comment]
![image](https://user-images.githubusercontent.com/20075869/89112816-8a30d500-d436-11ea-8031-8621769574af.png)
The FlipFlops.zip above has a gated clock. If you want to put your project onto an FPGA via the internal FPGA tools, this will throw an error "Gated Clock" and won't let the compile finished. The image I have included has a non-gated clock version of what Ben is looking for [hi btw] and will take up less resources on an FPGA.
