### ISSUE TITLE
Eclipse and development head

### ISSUE THREAD

**Issue by BFH-ktt1** [logisim-evolution/logisim-evolution#925]
Logisim can be build by gradle, however, when importing the gradle project in Eclipse the "standard" compilation/run/debug will fail due to a missing dependency on ```com.cburch.logisim.generated.BuildInfo```.
This is kind-of annoying.
I might think of a dummy ```com.cburch.logisim.generated.BuildInfo``` that gets overwritten by a gradle-build.

**Comment by MarcinOrlowski** [comment]
> Of course, as it is a generated file before doing anything in eclipse we have to do one time a gradle build

So it means `BuildInfo` is no longer up to date? Can we configure Eclipse builder to do something more (i.e. trigger anything) while building?

**Comment by davidhutchens** [comment]
The problem is that Eclipse refuses to add a source path that doesn't exist at the time of the import to Eclipse. So running ./gradlew genBuildInfo before importing the project adds the generated files source path, but it isn't added otherwise. I have looked for a hook to get Eclipse to run a gradle tasks before import, but I haven't found it.

There are a couple of other problems I've encountered in playing with it (that I can fix). I may have a way to fairly easily update Eclipse from within Eclipse but I have more tests to run. I hope to get a full understanding and a PR soon.

**Comment by MarcinOrlowski** [comment]
If that requires one manual build with Gradle before the import then this is acceptable (IMHO). What bothers me, is updating of BuildInfo class. Do I understand correctly that later, Eclipse will build using Gradle anyway? It's just matter of importing classes so Eclipse can i.e. index whatever, correct?

**Comment by davidhutchens** [comment]
Eclipse doesn't use gradle to build.  It scans the build file and extracts the info for Eclipse's own build. Thus, it never builds the generated files for us. It does, however, make gradle tasks available once it is loaded so I can generate the file (and even the final packages) from within Eclipse. I'm looking at how I can generate the file and then tell Eclipse to update its info. If I can get that to work reliably and fairly easily, I'll document it.

The fall-back position is to require a command line build of the generated file(s) before importing into Eclipse.

I may add a genFiles task that depends on genBuildInfo and use that in the description. The idea is that we can then add additional files (such as the flex file, #563) without needing to change the documentation. What do you think?

**Comment by MarcinOrlowski** [comment]
Let's do this: please do your tests and then update the developers docs. If we need build prior import - please add a note and invocation example to the docs. if we need to manually wire the task to make it auto-regenerated then great. Just make a note how. If not, then just add a note about rebuilding step is still manual for them. If they do care, because If they do not, then it is still fine.

**Comment by MarcinOrlowski** [comment]
Can I assign this ticket to you @davidhutchens ?

**Comment by davidhutchens** [comment]
Sure, assign me if you like. Your plan above matches what I was thinking.

**Comment by MarcinOrlowski** [comment]
You can rebuild BuildInfo class file (w/o rebuilding whole project) you can use `genBuildInfo` Gradle task.

**Comment by BFH-ktt1** [comment]
Resolved in #953 , closing
